### ISSUE TITLE
Missing device classes in jcl.dtd

### ISSUE THREAD

**Issue by mjpcger** [JavaPOSWorkingGroup/javapos-config-loader#3]
Several device classes are missing in jcl.dtd. Not critical, but ugly effects when looking at jpos.xml in editor (Devices of missing classes will be marked as erroneously). Here the list of missing device classes:
Belt, BillAcceptor, BillDispenser, CoinAcceptor, ElectronicValueRW, Gate, ImageScanner, ItemDispenser, Lights, RFIDScanner
Here an updated version, please add to next revision.
[jcl.zip](https://github.com/JavaPOSWorkingGroup/javapos-config-loader/files/5849761/jcl.zip)

**Comment by kuniss** [comment]
Yes, I encountered it also several times in editors which support XML validation. But never found the time to correct it.
It's a quite old issue.

But what do you think about correcting it itself and make a pull request?
It is quite easy, I promise!

Just clone this repository and open it by prefixing its link by "https://gitpod.io/#", e.g https://github.com/mjpcger/javapos-config-loader. This will open a full blown web IDE (you may need to register first at gitpod.io for free)
Then 

1. go to the terminal at the bottom view
2. make a branch at the terminal: `git branch fix-issue-3`
3. checkout the new branch: `git checkout fix-issue-3`
4. open jcl.dtd and make the corrections by opening the file using the file Explorer tab on the left
5. add the changes to the git index: `git add jcl.dtd`
6. commit your changes:  `git commit -m "your commit text" jcl.dtd`
7. push the change to your remote repo at GitHub: `git push origin fix-issue-3`
8. go to GitHub, check your branch is there and make a pull request for that branch to this original repo

For the git add/commit/push actions there are also GUI versions if you select the "Souce Control:Git" tab on the left and the according menus under the tree dots at the right upper corner in this tab.

That's all...

**Comment by mjpcger** [comment]
I do not understand what you mean. If I clone javapos-config-loader, it's on my local disk, not somewhere in https://github.com/mjpcger.
For what do I need gitpod.io? I can make a branch via the web interface, change and commit jcl.dtd via the web interface or via GitHub Desktop.
I didn't make any push origin request before, but I think this should be an easy step when I made the steps I decribed before?

**Comment by mjpcger** [comment]
Did it somehow, hopefully as desired.

**Comment by kuniss** [comment]
The typical workflow at GitHub is as follows, first you **fork** the repository you want to contribute to on GitHub. (I said "clone", but I meant "fork". Maybe, this confused you. Sorry for that.)

You did this already: https://github.com/mjpcger/javapos-config-loader

Now you clone your repository to your local dev environment (typical your local machine).

With gitpod.io you do not need this cloning step. The cloning is done automatically when opening the gitpod-io prefixed URL: https://gitpod.io/#https://github.com/mjpcger/javapos-config-loader

With that URL you get a full blown Web IDE which is quite similar to a local VS Code IDE. The whole setup is already done by project maintainer and one can start coding immediately. -- Zero friction coding. It's infrastructure as code...

So, gitpod.io makes contributing to open source quite easy. And, gitpod.io is free for open source projects (until 100 hourse per month per user, what is almost enough.)

**Comment by kuniss** [comment]
Solved with PR #4. Waiting for #5 to be solved before integrating it into a release.

**Comment by kuniss** [comment]
Solved with release [3.0.0](https://github.com/JavaPOSWorkingGroup/javapos-config-loader/releases/tag/3.0.0)
